// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Quiz.Migrations
{
    [DbContext(typeof(QuizContext))]
    partial class QuizContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quiz.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Foto");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.ToTable("Jogador");
                });

            modelBuilder.Entity("Quiz.Models.Questao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Opcao_a");

                    b.Property<string>("Opcao_b");

                    b.Property<string>("Opcao_c");

                    b.Property<string>("Opcao_d");

                    b.Property<string>("Pergunta");

                    b.Property<string>("Resposta_certa");

                    b.HasKey("Id");

                    b.ToTable("Questao");
                });

            modelBuilder.Entity("Quiz.Models.RespostaJogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JogadorId");

                    b.Property<int>("QuestaoId");

                    b.Property<string>("Resposta");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("QuestaoId");

                    b.ToTable("RespostaJogador");
                });

            modelBuilder.Entity("Quiz.Models.RespostaJogador", b =>
                {
                    b.HasOne("Quiz.Models.Jogador", "Jogador")
                        .WithMany("Questao")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Quiz.Models.Questao", "Questao")
                        .WithMany("Jogadores")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
